version: '3'
services:
  kdc:
    build: ./kdc
    volumes:
      - ./kdc/start.sh:/start.sh
      - keytab:/keytab
  cockroach:
    image: ubuntu:xenial-20170214
    depends_on:
      - kdc
    command: /cockroach/cockroach --certs-dir=/certs start-single-node --listen-addr cockroach
    environment:
      - KRB5_KTNAME=/keytab/crdb.keytab
    volumes:
      - ${CERTS_DIR:-../../.localcluster.certs}:/certs
      - keytab:/keytab
      - ${COCKROACH_BINARY:-../../../../cockroach-linux-2.6.32-gnu-amd64}:/cockroach/cockroach
  python:
    build: ./python
    user: "${UID}:${GID}"
    depends_on:
      - cockroach
    environment:
      - PGHOST=cockroach
      - PGPORT=26257
      - PGSSLMODE=require
    volumes:
      - ./kdc/krb5.conf:/etc/krb5.conf
      - ./python/start.sh:/start.sh
      - ${CERTS_DIR:-../../.localcluster.certs}:/certs
volumes:
  keytab:
