required = [
 "github.com/client9/misspell/cmd/misspell",
 "github.com/cockroachdb/errors",
 "github.com/cockroachdb/crlfmt",
 "github.com/cockroachdb/gostdlib/cmd/gofmt",
 "github.com/cockroachdb/gostdlib/x/tools/cmd/goimports",
 "github.com/cockroachdb/stress",
 "github.com/golang/dep/cmd/dep",
 "github.com/golang/lint/golint",
 "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
 "github.com/kevinburke/go-bindata/go-bindata",
 "github.com/kisielk/errcheck",
 "github.com/mattn/goveralls",
 "github.com/mibk/dupl",
 "github.com/wadey/gocovmerge",
 "golang.org/x/perf/cmd/benchstat",
 "golang.org/x/tools/cmd/goyacc",
 "golang.org/x/tools/cmd/stringer",
 "golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow",
 "honnef.co/go/tools/cmd/staticcheck",
]

noverify = [
  # We generate Go code with cgo configuration flags into go-libedit in order
   # to link against our own version of libedit.
  "github.com/knz/go-libedit"
]

ignored = [
  # Non-existent package used by a toy program in c-deps/protobuf.
  "github.com/google/protobuf/examples/tutorial",
]

# The collation tables must never change.
[[constraint]]
  name = "golang.org/x/text"
  revision = "470f45bf29f4147d6fbd7dfd0a02a848e49f5bf4"

[[constraint]]
  name = "go.etcd.io/etcd"
  branch = "master"

# Used for the API client; we want the latest.
[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/maruel/panicparse"
  revision = "f20d4c4d746f810c9110e21928d4135e1f2a3efa"

# https://github.com/getsentry/raven-go/pull/139
[[constraint]]
  name = "github.com/getsentry/raven-go"
  source = "https://github.com/cockroachdb/raven-go"

# Used for benchmarks, should be recent.
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

# https://github.com/montanaflynn/stats/releases (latest is 2015-10-14)
[[constraint]]
  name = "github.com/montanaflynn/stats"
  branch = "master"

# https://github.com/cockroachdb/circuitbreaker/commit/4f5b168
[[constraint]]
  name = "github.com/cockroachdb/circuitbreaker"
  branch = "master"

[[constraint]]
  name = "vitess.io/vitess"
  source = "https://github.com/cockroachdb/vitess"
  branch = "no-flag-names-parens"

# We want https://github.com/go-yaml/yaml/pull/381
[[constraint]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/cockroachdb/yaml"
  branch = "v2-encoding-style"

[[constraint]]
  name = "github.com/abourget/teamcity"
  source = "https://github.com/cockroachdb/teamcity"

# https://github.com/golang/dep/pull/2003
[[constraint]]
  name = "github.com/golang/dep"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/gogo/protobuf"
  source = "https://github.com/cockroachdb/gogoproto"
  branch = "v1.2.0-with-clone-fix"

# Pin to v1.1.0 because of https://github.com/kisielk/errcheck/issues/162.
[[constraint]]
  name = "github.com/kisielk/errcheck"
  version = "=v1.1.0"

# Pin to 2017.2.2 because of https://github.com/cockroachdb/cockroach/issues/33669.
[[constraint]]
  name = "honnef.co/go/tools"
  revision = "1f0868a609b73436e79b066f93c7f1a28c5dbae2"

# Test util - don't need to pin.
[[constraint]]
  name = "github.com/leanovate/gopter"
  branch = "master"

# github.com/openzipkin-contrib/zipkin-go-opentracing requires a newer
# version of thrift than is currently present in a release.
[[override]]
  name = "github.com/apache/thrift"
  revision = "2b7365c54f823013cc6a4760798051b22743c103"

# This repository has no releases (as of Jan 2019).
[[override]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=v1.21.2"

[prune]
  go-tests = true
  unused-packages = true

  # Avoid pruning projects containing needed protos.

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    unused-packages = false

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    unused-packages = false

  [[prune.project]]
    name = "github.com/prometheus/client_model"
    unused-packages = false

  # Contains packages with used C files.
  [[prune.project]]
    name = "github.com/knz/go-libedit"
    unused-packages = false
