required = [
 "github.com/client9/misspell/cmd/misspell",
 "github.com/cockroachdb/crlfmt",
 "github.com/cockroachdb/stress",
 "github.com/golang/dep/cmd/dep",
 "github.com/golang/lint/golint",
 "github.com/google/pprof",
 "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
 "github.com/jteeuwen/go-bindata/go-bindata",
 "github.com/kisielk/errcheck",
 "github.com/mattn/goveralls",
 "github.com/mibk/dupl",
 "github.com/wadey/gocovmerge",
 "golang.org/x/perf/cmd/benchstat",
 "golang.org/x/tools/cmd/goimports",
 "golang.org/x/tools/cmd/goyacc",
 "golang.org/x/tools/cmd/stringer",
]

ignored = [
  # Non-existent package used by a toy program in c-deps/protobuf.
  "github.com/google/protobuf/examples/tutorial",
]

# The collation tables must never change.
[[constraint]]
  name = "golang.org/x/text"
  revision = "470f45bf29f4147d6fbd7dfd0a02a848e49f5bf4"

# https://github.com/coreos/etcd/commit/f03ed33
#
# https://github.com/coreos/etcd/commit/ce0ad377
[[constraint]]
  name = "github.com/coreos/etcd"
  branch = "master"

# Used for the API client; we want the latest.
[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

# https://github.com/getsentry/raven-go/pull/139
[[constraint]]
  name = "github.com/getsentry/raven-go"
  source = "https://github.com/cockroachdb/raven-go"

# Used for benchmarks, should be recent.
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

# https://github.com/jteeuwen/go-bindata/pull/158
[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  source = "https://github.com/dim13/go-bindata"
  branch = "master"

# https://github.com/montanaflynn/stats/releases (latest is 2015-10-14)
[[constraint]]
  name = "github.com/montanaflynn/stats"
  branch = "master"

# https://github.com/rubyist/circuitbreaker/commit/af95830
[[constraint]]
  name = "github.com/rubyist/circuitbreaker"
  branch = "master"

# https://github.com/xwb1989/sqlparser/issues/31
# https://github.com/xwb1989/sqlparser/issues/32
[[constraint]]
  name = "github.com/xwb1989/sqlparser"
  source = "https://github.com/dt/sqlparser"

# The master version of go.uuid has an incompatible interface and (as
# of 2018-06-06) a serious bug. Don't upgrade without making sure
# that bug is fixed.
# https://github.com/cockroachdb/cockroach/issues/26332
[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

# github.com/docker/docker depends on a few functions not included in the
# latest release: reference.{FamiliarName,ParseNormalizedNamed,TagNameOnly}.
#
# https://github.com/docker/distribution/commit/429c75f
# https://github.com/docker/distribution/commit/2caeb61
[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

  # Avoid pruning projects containing needed protos.

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    unused-packages = false

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    unused-packages = false

  [[prune.project]]
    name = "github.com/prometheus/client_model"
    unused-packages = false

  # Contains packages with used C files.
  [[prune.project]]
    name = "github.com/knz/go-libedit"
    unused-packages = false
