services:
  cockroach:
    # We use a docker image mirror to avoid pulling from 3rd party repos, which sometimes have reliability issues.
    # See https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3462594561/Docker+image+sync for the details.
    image: us-east1-docker.pkg.dev/crl-docker-sync/docker-io/library/ubuntu:xenial-20210804
    command: /cockroach/cockroach start-single-node --insecure --listen-addr cockroach
    volumes:
      - ${COCKROACH_BINARY:-../../../../cockroach-linux-2.6.32-gnu-amd64}:/cockroach/cockroach
  flyway:
    depends_on:
      - cockroach
    image: us-east1-docker.pkg.dev/crl-docker-sync/docker-io/flyway/flyway:9.3
    volumes:
      - ./sql:/sql
    command: migrate -user=root -url=jdbc:postgresql://cockroach:26257/defaultdb -locations=filesystem:/sql
