apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v21.2.2
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=cockroachdb-0.cockroachdb"
        volumeMounts:
          - name: client-certs
            mountPath: /cockroach-certs
      restartPolicy: OnFailure
      volumes:
        - name: client-certs
          secret:
            secretName: cockroachdb.client.root
            defaultMode: 256

