version: '3'
services:
  postgres:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_INITDB_ARGS=--locale=C --encoding=UTF8
      - POSTGRES_HOST_AUTH_METHOD=trust
  cockroach1:
    # We use a docker image mirror to avoid pulling from 3rd party repos, which sometimes have reliability issues.
    # See https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3462594561/Docker+image+sync for the details.
    image: us-east1-docker.pkg.dev/crl-docker-sync/docker-mirror/docker.io/library/ubuntu:xenial-20170214
    command: /cockroach/cockroach start-single-node --insecure --listen-addr cockroach1
    volumes:
      - "${COCKROACH_PATH}:/cockroach/cockroach"
  cockroach2:
    # We use a docker image mirror to avoid pulling from 3rd party repos, which sometimes have reliability issues.
    # See https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3462594561/Docker+image+sync for the details.
    image: us-east1-docker.pkg.dev/crl-docker-sync/docker-mirror/docker.io/library/ubuntu:xenial-20170214
    command: /cockroach/cockroach start-single-node --insecure --listen-addr cockroach2
    volumes:
      - "${COCKROACH_PATH}:/cockroach/cockroach"
  test:
    # We use a docker image mirror to avoid pulling from 3rd party repos, which sometimes have reliability issues.
    # See https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3462594561/Docker+image+sync for the details.
    image: us-east1-docker.pkg.dev/crl-docker-sync/docker-mirror/docker.io/library/ubuntu:xenial-20170214
    environment:
      - COCKROACH_DEV_LICENSE=$COCKROACH_DEV_LICENSE
    # compare.test is a binary built by the pkg/compose/prepare.sh in non-bazel builds
    command: /compare/compare.test -each ${EACH} -test.run ${TESTS} -artifacts ${ARTIFACTS}
    depends_on:
      - postgres
      - cockroach1
      - cockroach2
    volumes:
      - "${COMPARE_DIR_PATH}:/compare"
