version: '3'
services:
  cockroach1:
    image: ubuntu:xenial-20170214
    command: /cockroach/cockroach start-single-node --insecure --listen-addr cockroach1
    volumes:
      - "${COCKROACH_PATH}:/cockroach/cockroach"
  cockroach2:
    image: ubuntu:xenial-20170214
    command: /cockroach/cockroach start-single-node --insecure --listen-addr cockroach2
    volumes:
      - "${COCKROACH_PATH}:/cockroach/cockroach"
  test:
    image: ubuntu:xenial-20170214
    environment:
      - COCKROACH_DEV_LICENSE=$COCKROACH_DEV_LICENSE
    # compare.test is a binary built by the pkg/compose/prepare.sh in non-bazel builds
    command: /compare/compare.test -each ${EACH} -test.run ${TESTS} -artifacts ${ARTIFACTS}
    depends_on:
      - cockroach1
      - cockroach2
    volumes:
      - "${COMPARE_DIR_PATH}:/compare"
