benchmarks:
  - display_name: Sysbench
    labels: ["SQL", "3node", "oltp_read_write"]
    name: "BenchmarkSysbench/SQL/3node/oltp_read_write"
    package: "pkg/sql/tests"
    runner_group: 1
    count: 15
    iterations: 1500
    compare_alpha: 0.025
    retries: 3
    metrics:
      - name: "sec/op"
        threshold: .3
      - name: "allocs/op"
        threshold: .1

  - display_name: Sysbench
    labels: ["KV", "3node", "oltp_read_only"]
    name: "BenchmarkSysbench/KV/3node/oltp_read_only"
    package: "pkg/sql/tests"
    runner_group: 2
    count: 15
    iterations: 3000
    compare_alpha: 0.025
    retries: 3
    metrics:
      - name: "sec/op"
        threshold: .4
      - name: "allocs/op"
        threshold: .1

  - display_name: Sysbench
    labels: ["KV", "3node", "oltp_write_only"]
    name: "BenchmarkSysbench/KV/3node/oltp_write_only"
    package: "pkg/sql/tests"
    runner_group: 2
    count: 15
    iterations: 3000
    compare_alpha: 0.025
    retries: 3
    metrics:
      - name: "sec/op"
        threshold: .4
      - name: "allocs/op"
        threshold: .1
