name: EXPERIMENTAL GitHub actions testing - master build
on:
  push:
    branches: [ master ]
jobs:
  test_job:
    runs-on: [self-hosted, basic_runner_group]
    steps:
      - uses: actions/checkout@v4
      - run: ./build/github/get-engflow-keys.sh
      - run: bazel test //pkg:all_tests --config engflowpublic --config crosslinux --jobs 300 --tls_client_certificate=/home/agent/engflow.crt --tls_client_key=/home/agent/engflow.key --remote_download_minimal --bes_keywords=branch=master --config=use_ci_timeouts
      - name: clean up
        if: always()
        run: rm -f /home/agent/engflow.*
